DROP PROCEDURE SelectByStreetNameAndDivisionName;
DROP PROCEDURE SelectAdministrativeDivisionUp;
DROP PROCEDURE BranchesSorted;
DROP PROCEDURE SelectDivisionIdsWithStreets;
DROP PROCEDURE SelectDivisionIdsWithStreetsCount;