//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błędne dane przy uwirzytylnieniu, sprawdż dane i zaloguj sie Ponownie.
        /// </summary>
        internal static string ExeptionMessageUnauthorizedUser {
            get {
                return ResourceManager.GetString("ExeptionMessageUnauthorizedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma istnieje nie mozna utworzyc ponownie.
        /// </summary>
        internal static string IsExistCompany {
            get {
                return ResourceManager.GetString("IsExistCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osoba istnieje niemożiwe ponowne utworzenie.
        /// </summary>
        internal static string IsExistPerson {
            get {
                return ResourceManager.GetString("IsExistPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzupełnij w Secretach Audience.
        /// </summary>
        internal static string NotConfiguredAudience {
            get {
                return ResourceManager.GetString("NotConfiguredAudience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzupełnij w Secretach Issuer.
        /// </summary>
        internal static string NotConfiguredIssuer {
            get {
                return ResourceManager.GetString("NotConfiguredIssuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzupełnij w Secretach Secret.
        /// </summary>
        internal static string NotConfiguredSecret {
            get {
                return ResourceManager.GetString("NotConfiguredSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie istnieje BranchOffer.
        /// </summary>
        internal static string NotExistBranchOffer {
            get {
                return ResourceManager.GetString("NotExistBranchOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybairze inny Email daress.
        /// </summary>
        internal static string NotUniqueContactEmail {
            get {
                return ResourceManager.GetString("NotUniqueContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz Inny Email.
        /// </summary>
        internal static string NotUniqueEmail {
            get {
                return ResourceManager.GetString("NotUniqueEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierzinny url segment.
        /// </summary>
        internal static string NotUniqueUrlSegment {
            get {
                return ResourceManager.GetString("NotUniqueUrlSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string ResponseSuccess {
            get {
                return ResourceManager.GetString("ResponseSuccess", resourceCulture);
            }
        }
    }
}
