//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za podanym Id/s oddaiło nie znaleziono.
        /// </summary>
        internal static string Branch_Cmd_Id_NotFound {
            get {
                return ResourceManager.GetString("Branch_Cmd_Id_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil Firmowy/Comapny juz istnieje.
        /// </summary>
        internal static string Company_Cmd_ExistProfile {
            get {
                return ResourceManager.GetString("Company_Cmd_ExistProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie posiadasz profilu Firmy/Company.
        /// </summary>
        internal static string Company_Cmd_Id_NotFound {
            get {
                return ResourceManager.GetString("Company_Cmd_Id_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz inny kontaktowy email dla Firmy/Company.
        /// </summary>
        internal static string Company_Cmd_NotUniqueContactEmail {
            get {
                return ResourceManager.GetString("Company_Cmd_NotUniqueContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpoisz inna nazwe firmy jesli ty jestes posiadaczem zgłoś problem z podana nazwa firmy.
        /// </summary>
        internal static string Company_Cmd_NotUniqueName {
            get {
                return ResourceManager.GetString("Company_Cmd_NotUniqueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpoisz inny REGON, jesli ty jestes posiadaczem zgłoś problem z podaym REGONem.
        /// </summary>
        internal static string Company_Cmd_NotUniqueRegon {
            get {
                return ResourceManager.GetString("Company_Cmd_NotUniqueRegon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz inny UrlSegment.
        /// </summary>
        internal static string Company_Cmd_NotUniqueUrlSegment {
            get {
                return ResourceManager.GetString("Company_Cmd_NotUniqueUrlSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem aplikacyjny, niepoprawna wartość bazodanowa CONSTRAINT Notification_CHECK_IsReadedByUser.
        /// </summary>
        internal static string Notification_Cmd_CHECK_IsReadedByUser {
            get {
                return ResourceManager.GetString("Notification_Cmd_CHECK_IsReadedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem aplikacyjny, nie isntnieje FK Notification_NotificationSender.
        /// </summary>
        internal static string Notification_Cmd_FK_Notification_NotificationSender {
            get {
                return ResourceManager.GetString("Notification_Cmd_FK_Notification_NotificationSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem aplikacyjny, nie isntnieje FK Notification_NotificationStatus.
        /// </summary>
        internal static string Notification_Cmd_FK_Notification_NotificationStatus {
            get {
                return ResourceManager.GetString("Notification_Cmd_FK_Notification_NotificationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono powiadomienia za podanym Id.
        /// </summary>
        internal static string Notification_Cmd_Id_NotFound {
            get {
                return ResourceManager.GetString("Notification_Cmd_Id_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil Osoby juz istnieje, nie ma moliwosci ponownie utworzyć.
        /// </summary>
        internal static string Person_Cmd_ExistProfile {
            get {
                return ResourceManager.GetString("Person_Cmd_ExistProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie posiadasz profilu osoby.
        /// </summary>
        internal static string Person_Cmd_Id_NotFound {
            get {
                return ResourceManager.GetString("Person_Cmd_Id_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem aplikacyjny, niepoprawna walidacja BirthDate po strone Backendu.
        /// </summary>
        internal static string Person_Cmd_IncorrectBirthDate {
            get {
                return ResourceManager.GetString("Person_Cmd_IncorrectBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem aplikacyjny, niepoprawny kod IsPublicProfile po strone Backendu.
        /// </summary>
        internal static string Person_Cmd_IncorrectIsPublicProfile {
            get {
                return ResourceManager.GetString("Person_Cmd_IncorrectIsPublicProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem aplikacyjny, niepoprawny kod IsStudent po strone Backendu.
        /// </summary>
        internal static string Person_Cmd_IncorrectIsStudent {
            get {
                return ResourceManager.GetString("Person_Cmd_IncorrectIsStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musisz wybrac inny email do kontaktu w profilu osoby.
        /// </summary>
        internal static string Person_Cmd_NotUniqueContactEmail {
            get {
                return ResourceManager.GetString("Person_Cmd_NotUniqueContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musisz wybrac nr. telefon email do kontaktu w profilu osoby.
        /// </summary>
        internal static string Person_Cmd_NotUniqueContactPhoneNum {
            get {
                return ResourceManager.GetString("Person_Cmd_NotUniqueContactPhoneNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musisz wybrac inny Url Segment w profilu osoby.
        /// </summary>
        internal static string Person_Cmd_NotUniqueUrlSegment {
            get {
                return ResourceManager.GetString("Person_Cmd_NotUniqueUrlSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za podanymi danymi nie zostało znaleziono rekordów.
        /// </summary>
        internal static string Url_Cmd_Ids_NotFound {
            get {
                return ResourceManager.GetString("Url_Cmd_Ids_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W podanych danych wystepuja duplikaty.
        /// </summary>
        internal static string Url_Cmd_PathConflicts {
            get {
                return ResourceManager.GetString("Url_Cmd_PathConflicts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JWT nie jest wygenerowany przez dny serwer, zaloguj sie ponownie.
        /// </summary>
        internal static string User_Jwt_IsNotGeneratedByThisServer {
            get {
                return ResourceManager.GetString("User_Jwt_IsNotGeneratedByThisServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem aplikacyjny, name z JWT powinien byc Guidem.
        /// </summary>
        internal static string User_Jwt_NameIsNotGuid {
            get {
                return ResourceManager.GetString("User_Jwt_NameIsNotGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie jest skonfigurowany Audience w UserSecrets.
        /// </summary>
        internal static string UserSecrets_Audience_NotConfigured {
            get {
                return ResourceManager.GetString("UserSecrets_Audience_NotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie jest skonfigurowany Issuer w UserSecrets .
        /// </summary>
        internal static string UserSecrets_Issuer_NotConfigured {
            get {
                return ResourceManager.GetString("UserSecrets_Issuer_NotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie jest skonfigurowany Secret w UserSecrets.
        /// </summary>
        internal static string UserSecrets_Secret_NotConfigured {
            get {
                return ResourceManager.GetString("UserSecrets_Secret_NotConfigured", resourceCulture);
            }
        }
    }
}
