//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages2() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Messages2", typeof(Messages2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za podanymi danymi nie znaleziono połączenia pomiedzy Ulicą a nazwą Miejscowości.
        /// </summary>
        internal static string Address_Collocation_NotFound {
            get {
                return ResourceManager.GetString("Address_Collocation_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za podanym Addressid nie znalezonono adresu.
        /// </summary>
        internal static string Address_Id_NotFound {
            get {
                return ResourceManager.GetString("Address_Id_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za podanym danymi  Oddział  urzytkownika nie zostało znalieziono.
        /// </summary>
        internal static string Branch_Id_NotFound {
            get {
                return ResourceManager.GetString("Branch_Id_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urzytkownik nie ma założonego conajmniej 1 oddziału aby utworzyc oferte, utwórz conajmniej 1 oddział.
        /// </summary>
        internal static string BranchOffer_Authorized_NotExistAnyBranchForCreatingOffer {
            get {
                return ResourceManager.GetString("BranchOffer_Authorized_NotExistAnyBranchForCreatingOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za podanymi danymi połączeń Ofert i Oddiałow urzytkownika nie zostało znalieziono.
        /// </summary>
        internal static string BranchOffer_Ids_NotFound {
            get {
                return ResourceManager.GetString("BranchOffer_Ids_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CharacteristicI_CharacteristicId_NotFound.
        /// </summary>
        internal static string CharacteristicI_CharacteristicId_NotFound {
            get {
                return ResourceManager.GetString("CharacteristicI_CharacteristicId_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urzytkownik nie posiada Firmy.
        /// </summary>
        internal static string Company_Ids_NotFound {
            get {
                return ResourceManager.GetString("Company_Ids_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DatabaseConstraint_ {
            get {
                return ResourceManager.GetString("DatabaseConstraint_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DatabaseConstraint_Branch_Address_NotFound {
            get {
                return ResourceManager.GetString("DatabaseConstraint_Branch_Address_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DatabaseConstraint_CHECK_BranchOffer_PublishEnd {
            get {
                return ResourceManager.GetString("DatabaseConstraint_CHECK_BranchOffer_PublishEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DatabaseConstraint_CHECK_BranchOffer_WorkEnd {
            get {
                return ResourceManager.GetString("DatabaseConstraint_CHECK_BranchOffer_WorkEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DatabaseConstraint_CHECK_BranchOffer_WorkStart {
            get {
                return ResourceManager.GetString("DatabaseConstraint_CHECK_BranchOffer_WorkStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DatabaseConstraint_CHECK_Offer_IsForStudents {
            get {
                return ResourceManager.GetString("DatabaseConstraint_CHECK_Offer_IsForStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DatabaseConstraint_CHECK_Offer_IsNegotiatedSalary {
            get {
                return ResourceManager.GetString("DatabaseConstraint_CHECK_Offer_IsNegotiatedSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DatabaseConstraint_CHECK_Offer_MaxSalary {
            get {
                return ResourceManager.GetString("DatabaseConstraint_CHECK_Offer_MaxSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DatabaseConstraint_CHECK_Offer_MinSalary {
            get {
                return ResourceManager.GetString("DatabaseConstraint_CHECK_Offer_MinSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DatabaseConstraint_Company_pk_Exist {
            get {
                return ResourceManager.GetString("DatabaseConstraint_Company_pk_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DatabaseConstraint_UNIQUE_Branch_UrlSegment {
            get {
                return ResourceManager.GetString("DatabaseConstraint_UNIQUE_Branch_UrlSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DatabaseConstraint_UNIQUE_Company_ContactEmail {
            get {
                return ResourceManager.GetString("DatabaseConstraint_UNIQUE_Company_ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DatabaseConstraint_UNIQUE_Company_Name {
            get {
                return ResourceManager.GetString("DatabaseConstraint_UNIQUE_Company_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DatabaseConstraint_UNIQUE_Company_Regon {
            get {
                return ResourceManager.GetString("DatabaseConstraint_UNIQUE_Company_Regon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DatabaseConstraint_UNIQUE_Company_UrlSegment {
            get {
                return ResourceManager.GetString("DatabaseConstraint_UNIQUE_Company_UrlSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DatabaseConstraint_UNIQUE_Url_Path {
            get {
                return ResourceManager.GetString("DatabaseConstraint_UNIQUE_Url_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login nie unikalny.
        /// </summary>
        internal static string DatabaseConstraint_UNIQUE_User_Login {
            get {
                return ResourceManager.GetString("DatabaseConstraint_UNIQUE_User_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podano niepoprawną datę.
        /// </summary>
        internal static string DateOnly_DateOnlyRequestDto_InvalidDate {
            get {
                return ResourceManager.GetString("DateOnly_DateOnlyRequestDto_InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za podanymi danymi Nie znaleziono Intership.
        /// </summary>
        internal static string Intership_Ids_NotFound {
            get {
                return ResourceManager.GetString("Intership_Ids_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie nzleziono danych za podanym Id.
        /// </summary>
        internal static string Notification_Id_NotFound {
            get {
                return ResourceManager.GetString("Notification_Id_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za podanymi danymi Ofert urzytkownika nie zostało znalieziono.
        /// </summary>
        internal static string Offer_Ids_NotFound {
            get {
                return ResourceManager.GetString("Offer_Ids_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiil Osoby nie istnieje.
        /// </summary>
        internal static string Person_Ids_NotFound {
            get {
                return ResourceManager.GetString("Person_Ids_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za podanymi danymi Rekrutacji nie znaleziono.
        /// </summary>
        internal static string Recruitment_Ids_NotFound {
            get {
                return ResourceManager.GetString("Recruitment_Ids_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za podanymi danymi zaakceptowane Rekrutacje nie znalezione.
        /// </summary>
        internal static string Recruitment_IdsAccepted_NotFound {
            get {
                return ResourceManager.GetString("Recruitment_IdsAccepted_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string ResponseSuccess {
            get {
                return ResourceManager.GetString("ResponseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za podanymi danymi Url  urzytkownika nie zostało znalieziono.
        /// </summary>
        internal static string Url_Ids_NotFound {
            get {
                return ResourceManager.GetString("Url_Ids_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem aplikacyjny, middlleware powinien zarzadzac odseparowywaniem urzytkownikow które nie istnieją.
        /// </summary>
        internal static string User_Ids_NotFound {
            get {
                return ResourceManager.GetString("User_Ids_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprawdż dane do logowania, i Zaloguj sie ponoiwnie .
        /// </summary>
        internal static string User_InputPassword_Invalid {
            get {
                return ResourceManager.GetString("User_InputPassword_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string User_Jwt_IsNotGeneratedByThisServer {
            get {
                return ResourceManager.GetString("User_Jwt_IsNotGeneratedByThisServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem Aplikacyjny, JWT Name jest Id usera po stronie Bazy danych który jest Guidem, zweryfikuj wszystkie przydaki co się stało.
        /// </summary>
        internal static string User_Jwt_NameIsNotGuid {
            get {
                return ResourceManager.GetString("User_Jwt_NameIsNotGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprawdż dane do logowania, i Zaloguj sie ponoiwnie.
        /// </summary>
        internal static string User_Login_NotFound {
            get {
                return ResourceManager.GetString("User_Login_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RefreshToken wygasł, zaloguj sie ponownie.
        /// </summary>
        internal static string User_RefreshToken_Expired {
            get {
                return ResourceManager.GetString("User_RefreshToken_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RefreshToken jest wartością pustą, wpisz swoj RefreshToken.
        /// </summary>
        internal static string User_RefreshToken_IsNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("User_RefreshToken_IsNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za podanymi danymi Problemów urzytkownika nie zostało znalieziono.
        /// </summary>
        internal static string UserProblem_Ids_NotFound {
            get {
                return ResourceManager.GetString("UserProblem_Ids_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W ramach wartstwy UI w  UserSecretach nie ma pola &quot;JwtData&quot; : &quot;Audience&quot; lub Plik UserSecret nie jst skonfigurowany poprawnie.
        /// </summary>
        internal static string UserSecrets_Audience_NotConfigured {
            get {
                return ResourceManager.GetString("UserSecrets_Audience_NotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W ramach wartstwy UI w  UserSecretach nie ma pola &quot;JwtData&quot; : &quot;Issuer&quot; lub Plik UserSecret nie jst skonfigurowany poprawnie.
        /// </summary>
        internal static string UserSecrets_Issuer_NotConfigured {
            get {
                return ResourceManager.GetString("UserSecrets_Issuer_NotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W ramach wartstwy UI w  UserSecretach nie ma pola &quot;JwtData&quot; : &quot;Secret&quot; lub Plik UserSecret nie jst skonfigurowany poprawnie.
        /// </summary>
        internal static string UserSecrets_Secret_NotConfigured {
            get {
                return ResourceManager.GetString("UserSecrets_Secret_NotConfigured", resourceCulture);
            }
        }
    }
}
