//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za podanymi danymi DivisionId nie został znaleziony.
        /// </summary>
        internal static string Address_Cmd_DivisionId_NotFound {
            get {
                return ResourceManager.GetString("Address_Cmd_DivisionId_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Połczenia pomiedy jednoska terytorialna a ulicamyi nie wyszukano.
        /// </summary>
        internal static string Address_Cmd_DivisionStreetCollocation_NotFound {
            get {
                return ResourceManager.GetString("Address_Cmd_DivisionStreetCollocation_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za podanymi danym Id address nie oształ wyszukany.
        /// </summary>
        internal static string Address_Cmd_Id_NotFound {
            get {
                return ResourceManager.GetString("Address_Cmd_Id_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za podanymi danymi StreetId nie został znaleziony.
        /// </summary>
        internal static string Address_Cmd_StreetId_NotFound {
            get {
                return ResourceManager.GetString("Address_Cmd_StreetId_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za podanymi Danymi nie wyszukano adresów/ adresu.
        /// </summary>
        internal static string Address_Query_Id_NotFound {
            get {
                return ResourceManager.GetString("Address_Query_Id_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addres nie został znaleziony.
        /// </summary>
        internal static string Branch_Cmd_Address_NotFound {
            get {
                return ResourceManager.GetString("Branch_Cmd_Address_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil Company/Firmy nie istnieje.
        /// </summary>
        internal static string Branch_Cmd_Company_NotExsist {
            get {
                return ResourceManager.GetString("Branch_Cmd_Company_NotExsist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za podanym Id/s oddaiło nie znaleziono.
        /// </summary>
        internal static string Branch_Cmd_Id_NotFound {
            get {
                return ResourceManager.GetString("Branch_Cmd_Id_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplikat po stronie Bazy danych, wartosc z danym UrlSegmentem juz istnieje.
        /// </summary>
        internal static string Branch_Cmd_UrlSegmet_DbDuplicate {
            get {
                return ResourceManager.GetString("Branch_Cmd_UrlSegmet_DbDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplikat w podanych danych, wartosc z danym UrlSegmentem juz istnieje.
        /// </summary>
        internal static string Branch_Cmd_UrlSegmet_InputDuplicate {
            get {
                return ResourceManager.GetString("Branch_Cmd_UrlSegmet_InputDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za podanymi danymi nie wyszukano Oddziału.
        /// </summary>
        internal static string BranchOffer_Cmd_Branch_NotFound {
            get {
                return ResourceManager.GetString("BranchOffer_Cmd_Branch_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za podanymi BranchOfferId, połaczen nie ozstało wyszukano.
        /// </summary>
        internal static string BranchOffer_Cmd_Ids_NotFound {
            get {
                return ResourceManager.GetString("BranchOffer_Cmd_Ids_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawna wartosc Daty konca publikacji, powinna zaczync sie conajmniej pozniej startu publikacji.
        /// </summary>
        internal static string BranchOffer_Cmd_Invalid_PublishEnd {
            get {
                return ResourceManager.GetString("BranchOffer_Cmd_Invalid_PublishEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawna wartosc WorkStart, powinna zaczync sie conajmniej tego samego dnia co PublishStart lub pózniej.
        /// </summary>
        internal static string BranchOffer_Cmd_Invalid_WorkEnd {
            get {
                return ResourceManager.GetString("BranchOffer_Cmd_Invalid_WorkEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawna wartosc daty pocztku Parcy, powinna zaczync sie conajmniej nastepnego dnia po zakonczeniu publikiacji.
        /// </summary>
        internal static string BranchOffer_Cmd_Invalid_WorkStart {
            get {
                return ResourceManager.GetString("BranchOffer_Cmd_Invalid_WorkStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za podanymi danymi nie wyszukano Oferty.
        /// </summary>
        internal static string BranchOffer_Cmd_Offer_NotFound {
            get {
                return ResourceManager.GetString("BranchOffer_Cmd_Offer_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za podanymi danymymi Ceha nie został wyszukana.
        /// </summary>
        internal static string Characteristic_Id_NotFound {
            get {
                return ResourceManager.GetString("Characteristic_Id_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za podanym Id komentarzu nie wyszukano.
        /// </summary>
        internal static string Comment_Cmd_Id_NotFound {
            get {
                return ResourceManager.GetString("Comment_Cmd_Id_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za podanymi danymi Stażu/Praktyk/Pracy nie wysukano.
        /// </summary>
        internal static string Comment_Cmd_Intership_NotFound {
            get {
                return ResourceManager.GetString("Comment_Cmd_Intership_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem aplikacyjny, nie wyszkakano comment type za podanym id.
        /// </summary>
        internal static string CommentType_Qwery_IdItemNotFound {
            get {
                return ResourceManager.GetString("CommentType_Qwery_IdItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil Firmowy/Comapny juz istnieje.
        /// </summary>
        internal static string Company_Cmd_ExistProfile {
            get {
                return ResourceManager.GetString("Company_Cmd_ExistProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie posiadasz profilu Firmy/Company.
        /// </summary>
        internal static string Company_Cmd_Id_NotFound {
            get {
                return ResourceManager.GetString("Company_Cmd_Id_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz inny kontaktowy email dla Firmy/Company.
        /// </summary>
        internal static string Company_Cmd_NotUniqueContactEmail {
            get {
                return ResourceManager.GetString("Company_Cmd_NotUniqueContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpoisz inna nazwe firmy jesli ty jestes posiadaczem zgłoś problem z podana nazwa firmy.
        /// </summary>
        internal static string Company_Cmd_NotUniqueName {
            get {
                return ResourceManager.GetString("Company_Cmd_NotUniqueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpoisz inny REGON, jesli ty jestes posiadaczem zgłoś problem z podaym REGONem.
        /// </summary>
        internal static string Company_Cmd_NotUniqueRegon {
            get {
                return ResourceManager.GetString("Company_Cmd_NotUniqueRegon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz inny UrlSegment.
        /// </summary>
        internal static string Company_Cmd_NotUniqueUrlSegment {
            get {
                return ResourceManager.GetString("Company_Cmd_NotUniqueUrlSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawna data.
        /// </summary>
        internal static string DateOnly_ValueAttribute_InvalidDate {
            get {
                return ResourceManager.GetString("DateOnly_ValueAttribute_InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer umowy powtarza sie, wybierz inny numer.
        /// </summary>
        internal static string Internship_Cmd_ContractNum_Duplicate {
            get {
                return ResourceManager.GetString("Internship_Cmd_ContractNum_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Praktyka/staż istnieje.
        /// </summary>
        internal static string Internship_Cmd_Exist {
            get {
                return ResourceManager.GetString("Internship_Cmd_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Praktyka/staż  za podanym Id nie istnieje.
        /// </summary>
        internal static string Internship_Cmd_Id_NotFound {
            get {
                return ResourceManager.GetString("Internship_Cmd_Id_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rekrutacja nie istnieje za podanym Id.
        /// </summary>
        internal static string Internship_Cmd_Recruitment_NotExist {
            get {
                return ResourceManager.GetString("Internship_Cmd_Recruitment_NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozytywnej rekrutacji nie isntieje za podanym Id.
        /// </summary>
        internal static string Internship_Cmd_Recruitment_PositiveNotExist {
            get {
                return ResourceManager.GetString("Internship_Cmd_Recruitment_PositiveNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem aplikacyjny, niepoprawna wartość bazodanowa CONSTRAINT Notification_CHECK_IsReadedByUser.
        /// </summary>
        internal static string Notification_Cmd_CHECK_IsReadedByUser {
            get {
                return ResourceManager.GetString("Notification_Cmd_CHECK_IsReadedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem aplikacyjny, nie isntnieje FK Notification_NotificationSender.
        /// </summary>
        internal static string Notification_Cmd_FK_Notification_NotificationSender {
            get {
                return ResourceManager.GetString("Notification_Cmd_FK_Notification_NotificationSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem aplikacyjny, nie isntnieje FK Notification_NotificationStatus.
        /// </summary>
        internal static string Notification_Cmd_FK_Notification_NotificationStatus {
            get {
                return ResourceManager.GetString("Notification_Cmd_FK_Notification_NotificationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono powiadomienia za podanym Id.
        /// </summary>
        internal static string Notification_Cmd_Id_NotFound {
            get {
                return ResourceManager.GetString("Notification_Cmd_Id_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za podanymi danymi nie wyszukano Cehy Oferty.
        /// </summary>
        internal static string Offer_Cmd_Characteristic_NotFound {
            get {
                return ResourceManager.GetString("Offer_Cmd_Characteristic_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za podanymi OfferIds, ofert nie ozstało wyszukano.
        /// </summary>
        internal static string Offer_Cmd_Ids_NotFound {
            get {
                return ResourceManager.GetString("Offer_Cmd_Ids_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem aplikacyjny, niepoprawna wrtosc IsForStudents.
        /// </summary>
        internal static string Offer_Cmd_Invalid_IsForStudents {
            get {
                return ResourceManager.GetString("Offer_Cmd_Invalid_IsForStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem aplikacyjny, niepoprawna wrtosc IsNegotiatedSalary.
        /// </summary>
        internal static string Offer_Cmd_Invalid_IsNegotiatedSalary {
            get {
                return ResourceManager.GetString("Offer_Cmd_Invalid_IsNegotiatedSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrtosc płacy minimalnej powinna byc taka sama jak minimalna lub wiecej.
        /// </summary>
        internal static string Offer_Cmd_Invalid_MaxSalary {
            get {
                return ResourceManager.GetString("Offer_Cmd_Invalid_MaxSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrtosc płacy minimalnej powinna byc 0 lub wiecej.
        /// </summary>
        internal static string Offer_Cmd_Invalid_MinSalary {
            get {
                return ResourceManager.GetString("Offer_Cmd_Invalid_MinSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj Id lub UrlSegment oddziału.
        /// </summary>
        internal static string Offer_Query_BranchData_NotGiven {
            get {
                return ResourceManager.GetString("Offer_Query_BranchData_NotGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj Id lub UrlSegment firmy.
        /// </summary>
        internal static string Offer_Query_CompanyData_NotGiven {
            get {
                return ResourceManager.GetString("Offer_Query_CompanyData_NotGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za podanymi danymi nie wyszukano zadnej oferty.
        /// </summary>
        internal static string Offer_Query_NotFound {
            get {
                return ResourceManager.GetString("Offer_Query_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za podanymi danymi addrees nie ostał znaleziony.
        /// </summary>
        internal static string Person_Cmd_Address_NotFound {
            get {
                return ResourceManager.GetString("Person_Cmd_Address_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil Osoby juz istnieje, nie ma moliwosci ponownie utworzyć.
        /// </summary>
        internal static string Person_Cmd_ExistProfile {
            get {
                return ResourceManager.GetString("Person_Cmd_ExistProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie posiadasz profilu osoby.
        /// </summary>
        internal static string Person_Cmd_Id_NotFound {
            get {
                return ResourceManager.GetString("Person_Cmd_Id_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem aplikacyjny, niepoprawna walidacja BirthDate po strone Backendu.
        /// </summary>
        internal static string Person_Cmd_IncorrectBirthDate {
            get {
                return ResourceManager.GetString("Person_Cmd_IncorrectBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem aplikacyjny, niepoprawny kod IsPublicProfile po strone Backendu.
        /// </summary>
        internal static string Person_Cmd_IncorrectIsPublicProfile {
            get {
                return ResourceManager.GetString("Person_Cmd_IncorrectIsPublicProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem aplikacyjny, niepoprawny kod IsStudent po strone Backendu.
        /// </summary>
        internal static string Person_Cmd_IncorrectIsStudent {
            get {
                return ResourceManager.GetString("Person_Cmd_IncorrectIsStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musisz wybrac inny email do kontaktu w profilu osoby.
        /// </summary>
        internal static string Person_Cmd_NotUniqueContactEmail {
            get {
                return ResourceManager.GetString("Person_Cmd_NotUniqueContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musisz wybrac nr. telefon email do kontaktu w profilu osoby.
        /// </summary>
        internal static string Person_Cmd_NotUniqueContactPhoneNum {
            get {
                return ResourceManager.GetString("Person_Cmd_NotUniqueContactPhoneNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musisz wybrac inny Url Segment w profilu osoby.
        /// </summary>
        internal static string Person_Cmd_NotUniqueUrlSegment {
            get {
                return ResourceManager.GetString("Person_Cmd_NotUniqueUrlSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak mozliwosci rekrutacji, oferta neważna.
        /// </summary>
        internal static string Recruitment_Cmd_BranchOffer_Expired {
            get {
                return ResourceManager.GetString("Recruitment_Cmd_BranchOffer_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak mozliwosci rekrutacji, oferta nieopublikowana.
        /// </summary>
        internal static string Recruitment_Cmd_BranchOffer_Future {
            get {
                return ResourceManager.GetString("Recruitment_Cmd_BranchOffer_Future", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za podanymi danymi BranchOffer nie istnieje.
        /// </summary>
        internal static string Recruitment_Cmd_BranchOffer_NotFound {
            get {
                return ResourceManager.GetString("Recruitment_Cmd_BranchOffer_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za podanym Id rekrutacja nie została znaleiona.
        /// </summary>
        internal static string Recruitment_Cmd_Id_NotFound {
            get {
                return ResourceManager.GetString("Recruitment_Cmd_Id_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak mozliwosci rekrutacji do włsanej firmy.
        /// </summary>
        internal static string Recruitment_Cmd_IntoHisCompany {
            get {
                return ResourceManager.GetString("Recruitment_Cmd_IntoHisCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem aplikacyjny, nieporawne dane Code IsAccepted.
        /// </summary>
        internal static string Recruitment_Cmd_IsAccepted_Invalid {
            get {
                return ResourceManager.GetString("Recruitment_Cmd_IsAccepted_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil Osoby nie isnieje.
        /// </summary>
        internal static string Recruitment_Cmd_Person_NotFound {
            get {
                return ResourceManager.GetString("Recruitment_Cmd_Person_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Już masz złozony wniosek, nie mozna ponownie ponownie złozyc wniosku o rekrutacje.
        /// </summary>
        internal static string Recruitment_Cmd_Recruitment_Exist {
            get {
                return ResourceManager.GetString("Recruitment_Cmd_Recruitment_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Response_Success {
            get {
                return ResourceManager.GetString("Response_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za podanymi danymi nie zostało znaleziono rekordów.
        /// </summary>
        internal static string Url_Cmd_Ids_NotFound {
            get {
                return ResourceManager.GetString("Url_Cmd_Ids_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W podanych danych wystepuja duplikaty.
        /// </summary>
        internal static string Url_Cmd_PathConflicts {
            get {
                return ResourceManager.GetString("Url_Cmd_PathConflicts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem aplikacyjny, nie wyszukany user za podanym ID.
        /// </summary>
        internal static string User_Cmd_Id_NotFound {
            get {
                return ResourceManager.GetString("User_Cmd_Id_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem aplikacyjny, niepoprawna wrtosc DatabaseBool.
        /// </summary>
        internal static string User_Cmd_Invalid_IsHideProfile {
            get {
                return ResourceManager.GetString("User_Cmd_Invalid_IsHideProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz inny login/email.
        /// </summary>
        internal static string User_Cmd_Login_NotUnique {
            get {
                return ResourceManager.GetString("User_Cmd_Login_NotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Token Pusty.
        /// </summary>
        internal static string User_Cmd_RefreshToken_IsNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("User_Cmd_RefreshToken_IsNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprawdz dane i zaloguj sie ponownie.
        /// </summary>
        internal static string User_Cmd_Unautorized {
            get {
                return ResourceManager.GetString("User_Cmd_Unautorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JWT nie jest wygenerowany przez dny serwer, zaloguj sie ponownie.
        /// </summary>
        internal static string User_Jwt_IsNotGeneratedByThisServer {
            get {
                return ResourceManager.GetString("User_Jwt_IsNotGeneratedByThisServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem aplikacyjny, name z JWT powinien byc Guidem.
        /// </summary>
        internal static string User_Jwt_NameIsNotGuid {
            get {
                return ResourceManager.GetString("User_Jwt_NameIsNotGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie jest skonfigurowany Audience w UserSecrets.
        /// </summary>
        internal static string UserSecrets_Audience_NotConfigured {
            get {
                return ResourceManager.GetString("UserSecrets_Audience_NotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie jest skonfigurowany Issuer w UserSecrets .
        /// </summary>
        internal static string UserSecrets_Issuer_NotConfigured {
            get {
                return ResourceManager.GetString("UserSecrets_Issuer_NotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie jest skonfigurowany Secret w UserSecrets.
        /// </summary>
        internal static string UserSecrets_Secret_NotConfigured {
            get {
                return ResourceManager.GetString("UserSecrets_Secret_NotConfigured", resourceCulture);
            }
        }
    }
}
