//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem aplikacyjny, w rmach podawanej listy DomainAdministrativeDivision nie istnieje AdministrativeDivisionId podawane w ramach konstruktora.
        /// </summary>
        internal static string Address_DivisionsHierarchy_NotFound {
            get {
                return ResourceManager.GetString("Address_DivisionsHierarchy_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem aplikacyjny, podawany DomainStreet nie jest tożsamy z DomainStreetId w konstruktorze.
        /// </summary>
        internal static string Address_Street_Invalid {
            get {
                return ResourceManager.GetString("Address_Street_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podana wartość nr mieszkania nie spełnia wymagań, może byc tylko wartośc liczbowa.
        /// </summary>
        internal static string ApartmentNumber_Value_Invalid {
            get {
                return ResourceManager.GetString("ApartmentNumber_Value_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem aplikacyjny, podawany address nie jest tożsamy z addressId podanym w konstruktorze, kontekst DomainBranch.
        /// </summary>
        internal static string Branch_Address_NotSameAddressId {
            get {
                return ResourceManager.GetString("Branch_Address_NotSameAddressId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data zakończenia publikacji nie może być mniejsza data utworzenia.
        /// </summary>
        internal static string BranchOffer_PublishEnd_Invalid {
            get {
                return ResourceManager.GetString("BranchOffer_PublishEnd_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data zakonczenia pracy nie może być wczesniej od daty pocztaku pracy.
        /// </summary>
        internal static string BranchOffer_WorkEnd_Invalid {
            get {
                return ResourceManager.GetString("BranchOffer_WorkEnd_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data poczatku pracy może byc najwcześniej kolejnego dnia po dacie zakończenia publikacji .
        /// </summary>
        internal static string BranchOffer_WorkStart_Invalid {
            get {
                return ResourceManager.GetString("BranchOffer_WorkStart_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podana wartosc Nr. budynku jest niepoprawna, powinna zaczynac sie od 1-9  i mogą zawierac sie znaki od A-Z także może byc&apos;/&apos; i numery.
        /// </summary>
        internal static string BuildingNumber_Value_Invalid {
            get {
                return ResourceManager.GetString("BuildingNumber_Value_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podana wartość oceny nie może byc mniejsza 0 i nie może byc większa od 5.
        /// </summary>
        internal static string CommentEvaluation_Value_Invalid {
            get {
                return ResourceManager.GetString("CommentEvaluation_Value_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podany Kod typu komentarza nie isntnieje.
        /// </summary>
        internal static string CommentType_Id_NotFound {
            get {
                return ResourceManager.GetString("CommentType_Id_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr. kontraktu nie może być pusty.
        /// </summary>
        internal static string ContractNumber_Value_IsNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("ContractNumber_Value_IsNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem aplikacyjny, Podana wartość kodu nie istnieje, sprawdż dane i popraw kod, Problem aplikacyjny związany z rożnymidanymi po stronie bazy danych i Backendzie.
        /// </summary>
        internal static string DatabaseBool_Code_Invalid {
            get {
                return ResourceManager.GetString("DatabaseBool_Code_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak możliwości zmiany statusu, sprawa została Zmknięta.
        /// </summary>
        internal static string DomainUserProblem_ProblemStatus_DoneOrAnnulled {
            get {
                return ResourceManager.GetString("DomainUserProblem_ProblemStatus_DoneOrAnnulled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podany adress Email nie spełnia wymagań.
        /// </summary>
        internal static string Email_Value_Invalid {
            get {
                return ResourceManager.GetString("Email_Value_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podana wartość srodka płatniczego nie spełnia wymagań, musi być maksymalnie po 2 liczbach po przecinku.
        /// </summary>
        internal static string Money_Value_Invalid {
            get {
                return ResourceManager.GetString("Money_Value_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W ramach podanych nalezy uzupełnić czy dane wynagrodzenie poddjae sie negociacjom.
        /// </summary>
        internal static string Offer_IsNegotiatedSalary_Empty {
            get {
                return ResourceManager.GetString("Offer_IsNegotiatedSalary_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksymalne wynagrodzenie nie może być mniejsze od minimalnego wynagrodzenia.
        /// </summary>
        internal static string Offer_MaxSalary_Invalid {
            get {
                return ResourceManager.GetString("Offer_MaxSalary_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem aplikacyjny, podawany address nie jest tożsamy z addressId podanym w konstruktorze, kontekst DomainPerson.
        /// </summary>
        internal static string Person_Address_NotSameAddressId {
            get {
                return ResourceManager.GetString("Person_Address_NotSameAddressId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podana data urodzenie jest niepoprawna, data urodzenia nie może być w prszyszłości.
        /// </summary>
        internal static string Person_BirthDate_InFuture {
            get {
                return ResourceManager.GetString("Person_BirthDate_InFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podana wartość nr. telefonu nie spełnia wymagań, powinno zwierać 9 cyfr.
        /// </summary>
        internal static string PhoneNumber_Value_Invalid {
            get {
                return ResourceManager.GetString("PhoneNumber_Value_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem aplikacyjny, Podany kod w ramach dostepnych ProblemStatus nie istnieje.
        /// </summary>
        internal static string ProblemStatus_Code_NotFound {
            get {
                return ResourceManager.GetString("ProblemStatus_Code_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podany nr. REGON nie spełnia wymagań, powinien zawierac 9 lub 14 cyfr.
        /// </summary>
        internal static string Regon_Value_Invalid {
            get {
                return ResourceManager.GetString("Regon_Value_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podany Segment Url nie spełnia wymagań, może zawierac zanki małe i duże od a-z i/lub &apos;-&apos;, &apos;_&apos;.
        /// </summary>
        internal static string SegmentUrl_Value_Invalid {
            get {
                return ResourceManager.GetString("SegmentUrl_Value_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scierza powinna zaczynac sie od https://... lub  http://....
        /// </summary>
        internal static string Url_Path_Invalid {
            get {
                return ResourceManager.GetString("Url_Path_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podawany id w ramach UrlType nie został znależiony.
        /// </summary>
        internal static string UrlType_Id_NotFound {
            get {
                return ResourceManager.GetString("UrlType_Id_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podany Kod pocztowy nie spełnia warunków, powinien zawierać tylko 5 cyfr.
        /// </summary>
        internal static string ZipCode_Value_Invalid {
            get {
                return ResourceManager.GetString("ZipCode_Value_Invalid", resourceCulture);
            }
        }
    }
}
