//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
<<<<<<< HEAD
        ///   Looks up a localized string similar to Numer mieszkania może zawierac tylko liczby od 1.
        /// </summary>
        internal static string InValidApartmentNumber {
            get {
                return ResourceManager.GetString("InValidApartmentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawny nr budynku.
        /// </summary>
        internal static string InValidBuildingNumber {
            get {
                return ResourceManager.GetString("InValidBuildingNumber", resourceCulture);
=======
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string IncorrectlementationBySqlClient {
            get {
                return ResourceManager.GetString("IncorrectlementationBySqlClient", resourceCulture);
>>>>>>> f6fddde1e373503f64b13b26b5c4a50fdf3a43d7
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocena nie może być poniżej 1 i nie może być powyżej 5.
        /// </summary>
        internal static string InValidCommentEvaluation {
            get {
                return ResourceManager.GetString("InValidCommentEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to za podanymi danymi CommentType nie istnieje.
        /// </summary>
        internal static string InValidCommentType {
            get {
                return ResourceManager.GetString("InValidCommentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ może byc &quot;y&quot; lub &quot;n&quot;.
        /// </summary>
        internal static string InValidDatabaseBool {
            get {
                return ResourceManager.GetString("InValidDatabaseBool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprwanie podany Email.
        /// </summary>
        internal static string InValidEmail {
            get {
                return ResourceManager.GetString("InValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartość srodka płaniczego nie może był po 2 liczbach po przecinku i nie moze byc ujemna.
        /// </summary>
        internal static string InValidMoney {
            get {
                return ResourceManager.GetString("InValidMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawny nr. telefonu, telefon zawiera tylko 9 cyfr.
        /// </summary>
        internal static string InValidPhoneNumber {
            get {
                return ResourceManager.GetString("InValidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGON, Niepoprawny, REGON, zawiera 9 lub 14 cyfr.
        /// </summary>
        internal static string InValidRegon {
            get {
                return ResourceManager.GetString("InValidRegon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment może zawieac tylko małe i duże łacinskie znaki, - _ .
        /// </summary>
        internal static string InValidSegmentUrl {
            get {
                return ResourceManager.GetString("InValidSegmentUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawny typ URL.
        /// </summary>
        internal static string InValidUrl {
            get {
                return ResourceManager.GetString("InValidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawny Kod pocztowy, on zwiera tylko 5 cyfr.
        /// </summary>
        internal static string InValidZipCode {
            get {
                return ResourceManager.GetString("InValidZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NotExistUserProblemStatus {
            get {
                return ResourceManager.GetString("NotExistUserProblemStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niezdefiniowany Typ Url.
        /// </summary>
        internal static string UndefinedUrlType {
            get {
                return ResourceManager.GetString("UndefinedUrlType", resourceCulture);
            }
        }
    }
}
